package pojos;
// Generated Jun 20, 2019 10:30:56 PM by Hibernate Tools 4.3.1



/**
 * Actor generated by hbm2java
 */
public class Actor  implements java.io.Serializable {


     private Integer actorid;
     private String actorname;
     private Integer actorage;

    public Actor() {
    }

    public Actor(String actorname, Integer actorage) {
       this.actorname = actorname;
       this.actorage = actorage;
    }
   
    public Integer getActorid() {
        return this.actorid;
    }
    
    public void setActorid(Integer actorid) {
        this.actorid = actorid;
    }
    public String getActorname() {
        return this.actorname;
    }
    
    public void setActorname(String actorname) {
        this.actorname = actorname;
    }
    public Integer getActorage() {
        return this.actorage;
    }
    
    public void setActorage(Integer actorage) {
        this.actorage = actorage;
    }




}


